name: CI

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - '!dev/**'
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.7.1"
          - "3.8"
          - "3.9"
          - "3.10"

    name: Check Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the stack
        run: docker-compose up -d mysql postgres presto trino

      - name: Install Poetry
        run: pip install poetry

      - name: Install package
        run: "poetry install"

      - name: Run unit tests
        env:
            DATADIFF_SNOWFLAKE_URI: '${{ secrets.DATADIFF_SNOWFLAKE_URI }}'
            DATADIFF_PRESTO_URI: '${{ secrets.DATADIFF_PRESTO_URI }}'
            DATADIFF_TRINO_URI: '${{ secrets.DATADIFF_TRINO_URI }}'
        run: poetry run unittest-parallel -j 16
